### ISSUE TITLE
Is it still updated?

### ISSUE THREAD

**Issue by honggesmile** [thien94/orb_slam3_ros_wrapper#1]
Thank you for your project, there are some todos waiting to be done, Is it still updated?

**Comment by thien94** [comment]
Hi, thank you for the question.

This repo is still being updated from time to time. However, I am holding off working on the to-dos until the [known issues](https://github.com/thien94/orb_slam3_ros_wrapper#current-known-limitations) are addressed since they are essential for the to-do stuff.

Hope this helps.
