### ISSUE TITLE
Frame Transformation

### ISSUE THREAD

**Issue by koksyuen** [thien94/orb_slam3_ros_wrapper#15]
![image](https://user-images.githubusercontent.com/72346941/181854118-73f53f50-0dc5-48e6-82a5-c021dac0457a.png)
Hi, does anyone understand why the transformation is written as shown in the source code? Any formula is followed?

What do the "on camera coordinate" and "on map coordinate" means?
I thought ORBSLAM3 shall take the estimated initial pose as the map coordinate origin, right?

**Comment by thien94** [comment]
Hi, sorry for the late reply.

The general formulation is `T_cam_ros = T_ros_orb x T_cam_orb x T_orb_ros`. `T_cam_orb` is the original pose from ORB-SLAM3, `T_cam_ros` is the transformed pose so that it follows ROS convention.

> What do the "on camera coordinate" and "on map coordinate" means?

These comments are a bit outdated, but the map coordinate refers to the ROS' world frame while camera coordinate refers to the camera frame in ORB-SLAM3.

> I thought ORBSLAM3 shall take the estimated initial pose as the map coordinate origin, right?

That is the case without IMU. When there is IMU, the world frame will be aligned with gravity.

**Comment by thien94** [comment]
The frame transformation has been removed in the latest version.
