### ISSUE TITLE
When the drone takes off, the tf is attached to the origin

### ISSUE THREAD

**Issue by romaster93** [thien94/orb_slam3_ros_wrapper#2]
I am trying to fly autonomously using orb slam3.

Currently, when the drone is taken off, the tf does not rise and is held.

The tail is always facing the map origin coordinates.

I will attach a video. Which seems to be the problem? Help.

stereo_not_inertial

https://youtu.be/rLEdxlnQJuE

**Comment by thien94** [comment]
My guess is that the problem comes from either:
1. Bad calibration parameters (camera intrinsic, IMU intrinsic, camera-IMU extrinsic). For this you will need to check and make sure everything is correct.
2. When IMU is involved, it is important to have movements in all 3D directions at the beginning in order to have good initialization. In your case, the drone takes off vertically right from the start, which renders the initialization process unsuccessful: even though there are output data, the results are not satisfactory.

Or a combination of both.
